### ISSUE TITLE
barbatus_typescript error after upgrading react to 15.3

### ISSUE THREAD

**Issue by itayb8** [barbatus/typescript#24]
Hello, 
I can't figure out why i have this compilation error. 
It started to happened after updating react and react dom to 15.3,
looking for clues what could it be,
thanks

**Comment by dagatsoin** [comment]
what is the error exactly?

**Comment by itayb8** [comment]
Debug Failure. False expression: 
   at Object.assert
   (/Users/itayb/.meteor/packages/barbatus_typescript/.0.3.4_1.b177iy++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/meteor-typescript/node_modules/typescript/lib/typescript.js:1721:23)
   at reportError

**Comment by barbatus** [comment]
@itayb8 This error message is succinct; it's not clear what is the problem.
So please provide a repo to reproduce or or run meteor with `TYPESCRIPT_LOG=3 meteor`.
Also makes sense to update the package since last version is 0.4.1

**Comment by itayb8** [comment]
Thank I'll try to update the package

**Comment by barbatus** [comment]
obsolete
